language: python
python:
  - "3.6"
  - "3.8"
env:
  #- DJANGO_VERSION=1.11.29
  - DJANGO_VERSION=2.2.16
  - DJANGO_VERSION=3.0.10
  - DJANGO_VERSION=3.1.2
# command to install dependencies
before_install:
  - sudo apt-get --quiet update
  - sudo apt-get install pandoc
  - sudo pip install --upgrade setuptools
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements_travis.txt
# command to run tests
script:
  - mv settings_default.py settings.py
  - python manage.py test