# Generated by Django 2.0.13 on 2020-09-29 12:53

from django.db import migrations, models
import django.db.models.deletion
import markymark.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('base', models.TextField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('patch', models.TextField(blank=True, null=True)),
                ('conflicts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Master', 'Master'), ('Version', 'Version'), ('Conflicted', 'Conflicted'), ('History', 'History'), ('Reconciled', 'Reconciled')], default='Master', max_length=12)),
                ('content', markymark.fields.MarkdownField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barney_version.Version')),
            ],
            options={
                'verbose_name': 'Versions',
                'verbose_name_plural': 'Version',
            },
        ),
    ]
