# Generated by Django 3.1.1 on 2020-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_auto_20201003_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
