# Generated by Django 3.1.1 on 2020-10-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20201003_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('Master', 'Master'), ('Version', 'Version'), ('Conflicted', 'Conflicted'), ('History', 'History'), ('Reconciled', 'Reconciled'), ('Merged', 'Merged'), ('Merqe_req', 'Merge Request')], default='Master', max_length=12),
        ),
    ]
