# Generated by Django 2.0.13 on 2020-09-15 15:14

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion
import markymark.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('data_creazione', models.DateTimeField(blank=True, null=True)),
                ('data_modifica', models.DateTimeField(blank=True, null=True)),
                ('contenuto', markymark.fields.MarkdownField()),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Varianti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modifica', models.DateTimeField(blank=True, null=True)),
                ('contenuto_patch', models.TextField(blank=True, null=True)),
                ('contenuto_variante', markymark.fields.MarkdownField(blank=True, null=True)),
                ('contenuto_sorgente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Documenti')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Varianti',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('patch', models.TextField(blank=True, null=True)),
                ('gigi', models.TextField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
            options={
                'verbose_name': 'Versions',
                'verbose_name_plural': 'Version',
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
