
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-13 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markymark.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('base', models.TextField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('patch', models.TextField(blank=True, null=True)),
                ('conflicts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Master', 'Master'), ('Version', 'Version'), ('Conflicted', 'Conflicted'), ('History', 'History'), ('Reconciled', 'Reconciled'), ('Merged', 'Merged'), ('Merqe_req', 'Merge Request')], default='Master', max_length=12)),
                ('content', markymark.fields.MarkdownField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.Version')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
    ]
