# Generated by Django 2.0.13 on 2021-01-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='condiv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
