# Generated by Django 2.0.13 on 2020-09-15 15:37

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='contenuto',
            field=computed_property.fields.ComputedTextField(blank=True, compute_from='calculation', editable=False, null=True),
        ),
    ]
