# Generated by Django 2.0.13 on 2020-09-16 09:46

from django.db import migrations
import markymark.fields


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_version_contenuto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='contenuto',
        ),
        migrations.RemoveField(
            model_name='version',
            name='gigi',
        ),
        migrations.AddField(
            model_name='version',
            name='content',
            field=markymark.fields.MarkdownField(blank=True, null=True),
        ),
    ]
