# Generated by Django 2.0.13 on 2020-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20200916_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='base',
            field=models.TextField(blank=True, null=True),
        ),
    ]
